#!/usr/bin/env python3
"""
NEXUS-IOT Device Client - Enterprise Edition
Generated by NEXUS-IOT Platform
"""

import socketio
import base64
import json
import time
import os
import sys
import platform
import psutil
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes
import pyautogui
import io
from PIL import Image
import logging
from datetime import datetime
import threading
import queue

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class DeviceClient:
    def __init__(self, api_key, account_id, device_name):
        self.api_key = api_key
        self.account_id = account_id
        self.device_name = device_name
        self.device_id = None
        self.session_key = None
        self.is_streaming = False
        self.is_active = True
        self.command_queue = queue.Queue()
        self.sio = socketio.Client()
        self.setup_handlers()
        self.register_device()
        
    def encrypt(self, data):
        if not self.session_key:
            raise Exception("Session key not established")
        cipher = AES.new(self.session_key, AES.MODE_GCM)
        ciphertext, tag = cipher.encrypt_and_digest(json.dumps(data).encode())
        return {
            'encrypted': base64.b64encode(ciphertext).decode(),
            'iv': base64.b64encode(cipher.nonce).decode(),
            'tag': base64.b64encode(tag).decode()
        }
    
    def decrypt(self, encrypted_data):
        if not self.session_key:
            raise Exception("Session key not established")
        cipher = AES.new(self.session_key, AES.MODE_GCM, 
                        nonce=base64.b64decode(encrypted_data['iv']))
        decrypted = cipher.decrypt_and_verify(
            base64.b64decode(encrypted_data['encrypted']),
            base64.b64decode(encrypted_data['tag'])
        )
        return json.loads(decrypted.decode())
    
    def register_device(self):
        import requests
        try:
            response = requests.post(
                'http://localhost:5000/api/v1/devices',
                headers={'X-API-Key': self.api_key},
                json={
                    'name': self.device_name,
                    'deviceType': platform.system(),
                    'hostname': platform.node(),
                    'platform': platform.platform()
                }
            )
            if response.status_code == 201:
                data = response.json()
                self.device_id = data['device']['deviceId']
                self.session_key = base64.b64decode(data['device']['sessionKey'])
                logger.info(f"Device registered: {self.device_id}")
            else:
                logger.error(f"Registration failed: {response.text}")
                sys.exit(1)
        except Exception as e:
            logger.error(f"Registration error: {e}")
            sys.exit(1)
    
    def setup_handlers(self):
        @self.sio.on('connect')
        def on_connect():
            logger.info("Connected to server")
            auth_data = self.encrypt({
                'deviceId': self.device_id,
                'apiKey': self.api_key,
                'type': 'authenticate'
            })
            self.sio.emit('device:auth', auth_data)
        
        @self.sio.on('disconnect')
        def on_disconnect():
            logger.info("Disconnected from server")
        
        @self.sio.on('command:start')
        def on_start(data):
            logger.info("Received START command")
            self.is_streaming = True
        
        @self.sio.on('command:stop')
        def on_stop(data):
            logger.info("Received STOP command")
            self.is_streaming = False
        
        @self.sio.on('command:text')
        def on_text(data):
            decrypted = self.decrypt(data)
            text = decrypted.get('text', '')
            logger.info(f"Received TEXT: {text}")
            self.on_text_received(text)
        
        @self.sio.on('command:voice')
        def on_voice(data):
            decrypted = self.decrypt(data)
            command = decrypted.get('command', '')
            logger.info(f"Received VOICE: {command}")
            self.on_voice_command(command)
        
        @self.sio.on('command:screenshot')
        def on_screenshot(data):
            logger.info("Received SCREENSHOT command")
            self.take_screenshot()
        
        @self.sio.on('command:restart')
        def on_restart(data):
            logger.info("Received RESTART command")
            self.on_restart_device()
    
    def take_screenshot(self):
        try:
            screenshot = pyautogui.screenshot()
            buffer = io.BytesIO()
            screenshot.save(buffer, format='JPEG', quality=70)
            frame = base64.b64encode(buffer.getvalue()).decode()
            encrypted_frame = self.encrypt({
                'frame': frame,
                'timestamp': time.time(),
                'deviceId': self.device_id,
                'type': 'screenshot'
            })
            self.sio.emit('device:frame', encrypted_frame)
            logger.info("Screenshot captured")
        except Exception as e:
            logger.error(f"Screenshot failed: {e}")
    
    def get_system_metrics(self):
        try:
            return {
                'cpu': psutil.cpu_percent(interval=1),
                'ram': psutil.virtual_memory().percent,
                'disk': psutil.disk_usage('/').percent,
                'timestamp': time.time()
            }
        except:
            return {'cpu': 0, 'ram': 0, 'disk': 0, 'timestamp': time.time()}
    
    def start_streaming(self):
        self.sio.connect('http://localhost:5000')
        logger.info(f"Device {self.device_name} connected")
        while self.is_active:
            try:
                if self.is_streaming:
                    screenshot = pyautogui.screenshot()
                    buffer = io.BytesIO()
                    screenshot.save(buffer, format='JPEG', quality=60)
                    frame = base64.b64encode(buffer.getvalue()).decode()
                    metrics = self.get_system_metrics()
                    data = {
                        'frame': frame,
                        'metrics': metrics,
                        'timestamp': time.time(),
                        'deviceId': self.device_id,
                        'type': 'stream'
                    }
                    encrypted_data = self.encrypt(data)
                    self.sio.emit('device:frame', encrypted_data)
                    encrypted_metrics = self.encrypt({
                        'metrics': metrics,
                        'deviceId': self.device_id
                    })
                    self.sio.emit('device:metrics', encrypted_metrics)
                time.sleep(0.5)
            except KeyboardInterrupt:
                logger.info("Streaming stopped")
                break
            except Exception as e:
                logger.error(f"Streaming error: {e}")
                time.sleep(2)
    
    def on_text_received(self, text):
        print(f"[TEXT] {text}")
    
    def on_voice_command(self, command):
        print(f"[VOICE] {command}")
    
    def on_restart_device(self):
        logger.info("Restarting device client...")
        sys.exit(0)

if __name__ == "__main__":
    import sys
    import getpass
    
    API_KEY = "YOUR_API_KEY_HERE"
    ACCOUNT_ID = "YOUR_ACCOUNT_ID_HERE"
    DEVICE_NAME = "My_Device"
    
    device = DeviceClient(API_KEY, ACCOUNT_ID, DEVICE_NAME)
    try:
        device.start_streaming()
    except KeyboardInterrupt:
        logger.info("Device stopped")
    except Exception as e:
        logger.error(f"Device error: {e}")
        sys.exit(1)